# Generated by Django 5.2.4 on 2025-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('technology', models.TextField(blank=True, verbose_name='Технология производства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/reel/DIwSz3Doxrl/?igsh=ZWg2b2xqcnh4ODF2', verbose_name='Ссылка на Instagram')),
            ],
        ),
    ]
