# Generated by Django 5.2.4 on 2025-08-03 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, ГОСТ Р 51074-2003, ISO 22000', max_length=200, verbose_name='Название сертификата')),
                ('description', models.TextField(help_text='Краткое описание стандарта или сертификата', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Файл изображения сертификата', upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения сертификатов (меньше - выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы сертификат отображался на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Файл изображения для галереи', upload_to='gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, verbose_name='Альтернативный текст (Alt)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения изображений (меньше - выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы изображение отображалось в галерее', verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('technology', models.TextField(blank=True, verbose_name='Технология производства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/eda__bez.vreda?igsh=eHR2bjNoNjNmcnA4', verbose_name='Ссылка на Instagram')),
                ('weight', models.TextField(help_text='Например: 300 г (2 штуки)', verbose_name='Вес / фасовка')),
                ('composition', models.TextField(help_text='Каждый ингредиент с новой строки', verbose_name='Состав')),
                ('calories', models.PositiveSmallIntegerField(help_text='на 100 г', verbose_name='Калории (ккал)')),
                ('proteins', models.DecimalField(decimal_places=1, help_text='на 100 г', max_digits=4, verbose_name='Белки (г)')),
                ('fats', models.DecimalField(decimal_places=1, help_text='на 100 г', max_digits=4, verbose_name='Жиры (г)')),
                ('carbs', models.DecimalField(decimal_places=1, help_text='на 100 г', max_digits=4, verbose_name='Углеводы (г)')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('screenshot', models.ImageField(blank=True, help_text='Можно загрузить скриншот отзыва из Instagram', null=True, upload_to='reviews/', verbose_name='Скриншот из Instagram')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
