# Generated by Django 5.2.4 on 2025-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Сахара, Лактозы', max_length=50, verbose_name='Название')),
                ('icon', models.ImageField(help_text='SVG или PNG (рекомендуется 100x100)', upload_to='exclusions/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Меньше — выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Элемент "Не содержит"',
                'verbose_name_plural': 'Элементы "Не содержит"',
                'ordering': ['order'],
            },
        ),
    ]
