# Generated by Django 5.2.4 on 2025-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/reel/DIwSz3Doxrl/?igsh=ZWg2b2xqcnh4ODF2', max_length=300, verbose_name='Ссылка на Instagram'),
        ),
    ]
