# Generated by Django 5.2.4 on 2025-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.URLField(blank=True, default='https://www.instagram.com/eda__bez.vreda?igsh=eHR2bjNoNjNmcnA4', verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
