# Generated by Django 5.2.4 on 2025-07-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_instagram_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, ГОСТ Р 51074-2003, ISO 22000', max_length=200, verbose_name='Название сертификата')),
                ('description', models.TextField(help_text='Краткое описание стандарта или сертификата', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Файл изображения сертификата', upload_to='certificates/', verbose_name='Изображение сертификата')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения сертификатов (меньше - выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы сертификат отображался на сайте', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
    ]
