# Generated by Django 5.2.4 on 2025-07-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Файл изображения для галереи', upload_to='gallery/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, verbose_name='Альтернативный текст (Alt)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Определяет порядок отображения изображений (меньше - выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, чтобы изображение отображалось в галерее', verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
